apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
  kind: BackupTarget
  metadata:
    creationTimestamp: "2024-08-06T01:55:48Z"
    generation: 149
    managedFields:
    - apiVersion: longhorn.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:backupTargetURL: {}
          f:credentialSecret: {}
          f:pollInterval: {}
          f:syncRequestedAt: {}
      manager: longhorn-manager
      operation: Update
      time: "2024-08-06T14:11:40Z"
    - apiVersion: longhorn.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:available: {}
          f:conditions: {}
          f:lastSyncedAt: {}
          f:ownerID: {}
      manager: longhorn-manager
      operation: Update
      subresource: status
      time: "2024-08-06T14:12:16Z"
    name: default
    namespace: longhorn-system
    resourceVersion: "770219"
    uid: d1796b4d-bce0-4341-9f0c-49d5a594731a
  spec:
    backupTargetURL: nfs://server.unraid:/mnt/user/koat/harvester
    credentialSecret: "null"
    pollInterval: 5m0s
    syncRequestedAt: "2024-08-06T14:11:40Z"
  status:
    available: false
    conditions:
    - lastProbeTime: "null"
      lastTransitionTime: "2024-08-06T01:55:54Z"
      message: |-
        failed to list backup volumes in nfs://server.unraid:/mnt/user/koat/harvester: error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2/longhorn backup ls --volume-only nfs://server.unraid:/mnt/user/koat/harvester], output failed to execute: ls [-1 /var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes], output ls: cannot access '/var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes': Permission denied
        , error exit status 2
        , stderr time="2024-08-06T14:12:16Z" level=warning msg="Trying reading mount point /var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester to make sure it is healthy" func=util.EnsureMountPoint file="util.go:309" pkg=nfs
        time="2024-08-06T14:12:16Z" level=info msg="Loaded driver for nfs://server.unraid:/mnt/user/koat/harvester" func=nfs.initFunc file="nfs.go:91" pkg=nfs
        time="2024-08-06T14:12:16Z" level=warning msg="Failed to list first level dirs for path backupstore/volumes" func=backupstore.getVolumeNames file="config.go:183" error="failed to execute: ls [-1 /var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes], output ls: cannot access '/var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes': Permission denied\n, error exit status 2" pkg=backupstore
        time="2024-08-06T14:12:16Z" level=error msg="failed to execute: ls [-1 /var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes], output ls: cannot access '/var/lib/longhorn-backupstore-mounts/server_unraid/mnt/user/koat/harvester/backupstore/volumes': Permission denied\n, error exit status 2" func=main.ResponseLogAndError file="main.go:47"
        : exit status 1
      reason: Unavailable
      status: "True"
      type: Unavailable
    lastSyncedAt: "null"
    ownerID: harvesterdev1
kind: List
metadata:
  continue: "null"
  resourceVersion: "770282"
